import { ListView } from "std-widgets.slint";

export struct UiActivity {
    name: string,
    image: image,
    teacher: string,
}

component ActivityWidget {
    in property <string> name: "Name";
    in property <image> image: @image-url("assets/icon/activity.svg");
    in property <string> teacher: "Teacher";
    HorizontalLayout {
        HorizontalLayout{
            alignment: start;
            Image {
                min-height: 32px;
                min-width: 32px;
                preferred-height: 32px;
                preferred-width: 32px;
                source: image;
            }
        }
        HorizontalLayout{
            alignment: center;
            VerticalLayout {
                alignment: center;
                name-text:= Text {
                    horizontal-alignment: left;
                    text: name;
                }
                Text {
                    horizontal-alignment: left;
                    font-size: 10px;
                    text: teacher;
                    color: gray;
                }
            }
        }
    }
}
export component ActivityList {
    in property <[UiActivity]> activities: [
        {name: "Name", image: @image-url("assets/icon/activity.svg"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/icon/activity.svg"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/icon/activity.svg"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/icon/activity.svg"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/icon/activity.svg"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/icon/activity.svg"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/icon/activity.svg"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/icon/activity.svg"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/icon/activity.svg"), teacher: "Teacher"},
    ];
    ListView {
        for activity in activities: ActivityWidget {
            name: activity.name;
            image: activity.image;
            teacher: activity.teacher;
        }
    }
}