import { ListView } from "std-widgets.slint";

export struct UiCourse {
    name: string,
    image: image,
    teacher: string,
}

component CourseWidget {
    in property <string> name: "Name";
    in property <image> image: @image-url("assets/1.png");
    in property <string> teacher: "Teacher";
    HorizontalLayout {
        HorizontalLayout{
            alignment: start;
            Image {
                min-height: 32px;
                min-width: 32px;
                preferred-height: 32px;
                preferred-width: 32px;
                source: image;
            }
        }
        HorizontalLayout{
            alignment: center;
            VerticalLayout {
                alignment: center;
                name-text:= Text {
                    text: name;
                }
                Text {
                    font-size: 10px;
                    text: teacher;
                    color: gray;
                }
            }
        }
    }
}
export component CourseList {
    in property <[UiCourse]> courses: [
        {name: "Name", image: @image-url("assets/1.png"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/1.png"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/1.png"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/1.png"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/1.png"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/1.png"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/1.png"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/1.png"), teacher: "Teacher"},
        {name: "Name", image: @image-url("assets/1.png"), teacher: "Teacher"},
    ];
    ListView {
        for course in courses: CourseWidget {
            name: course.name;
            image: course.image;
            teacher: course.teacher;
        }
    }
}