import { ListView , VerticalBox} from "std-widgets.slint";

export struct UiCourse {
    name: string,
    teacher: string,
}

component CourseWidget {
    in property <string> name: "Name";
    in property <string> teacher: "Teacher";
    in property <int> id;
    callback clicked <=> touch-area.clicked;
    touch-area:= TouchArea {
        VerticalLayout { 
            name-text:= Text {
                horizontal-alignment: left;
                font-size: 15px;
                text: name;
            }
            Text {
                horizontal-alignment: left;
                font-size: 10px;
                text: teacher;
                color: gray;
            }
        }
    }
}
export component CourseList {
    in property <[UiCourse]> courses: [
        {name: "Name", teacher: "Teacher"},
        {name: "Name", teacher: "Teacher"},
        {name: "Name", teacher: "Teacher"},
        {name: "Name", teacher: "Teacher"},
        {name: "Name", teacher: "Teacher"},
        {name: "Name", teacher: "Teacher"},
        {name: "Name", teacher: "Teacher"},
        {name: "Name", teacher: "Teacher"},
        {name: "Name", teacher: "Teacher"},
    ];
    ListView {
        for course in courses: CourseWidget {
            name: course.name;
            teacher: course.teacher;
        }
    }
}