import { CourseList } from "courselist.slint";
import { ActivityList } from "activitylist.slint";
import { AccountList } from "accountlist.slint";
import { ScrollView } from "std-widgets.slint";
import { UiCourse } from "courselist.slint";
import { UiActivity } from "activitylist.slint";
import { UiAccount } from "accountlist.slint";
component WidgetBar {
    callback switch-to-course-page <=> course-bar.clicked;
    callback switch-to-account-page <=> account-bar.clicked;
    callback switch-to-activity-page <=> activity-bar.clicked;
    in property <length> size;
    min-height: size;
    HorizontalLayout {
        course-bar:= TouchArea {
            Image {
                source: @image-url("assets/icon/course.svg");
            }
        }
        activity-bar:= TouchArea {
            Image {
                source: @image-url("assets/icon/activity.svg");
            }
        }
        account-bar:= TouchArea {
            Image {
                source: @image-url("assets/icon/account.svg");
            }
        }
    }
}

enum HomePage{ course-page, activity-page, account-page }

export component MainWidget {
    in property <length> size: 32px;
    property <HomePage> page: HomePage.course-page;
    in property <[UiCourse]> courses <=> course-list.courses;
    in property <[UiActivity]> activities <=> activity-list.activities;
    in property <[UiAccount]> accounts <=> account-list.accounts;
    VerticalLayout {
        scroll:= Rectangle {
            min-height: size * 9;
            clip: true;
            home-widget:= HorizontalLayout {
                y: 0px;
                width: bar.width * 3;
                height: scroll.height;
                course-list:= CourseList {}
                activity-list:= ActivityList {}
                account-list:= AccountList {}
                animate x {
                    easing: ease-in-out;
                    duration: 200ms;
                }
            }
            vertical-stretch: 9;
        }
        bar:= WidgetBar {
            size: size;
            switch-to-course-page => {
                page = HomePage.course-page;
            }
            switch-to-activity-page => {
                page = HomePage.activity-page;
            }
            switch-to-account-page => {
                page = HomePage.account-page;
            }
            vertical-stretch: 1;
        }
        states [
            course-page when page == HomePage.course-page: {
                home-widget.x: 0px;
                scroll.forward-focus: course-list;
            }
            activity-page when page == HomePage.activity-page: {
                home-widget.x: -bar.width;
                scroll.forward-focus: activity-list;
            }
            account-page when page == HomePage.account-page: {
                home-widget.x: -bar.width * 2;
                scroll.forward-focus: account-list;
            }
        ]
    }
}